server:
  port: 8095
spring:
  application:
    name: gateway-service
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: core, swagger, nacos
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 添加favicon.ico路由
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              url-expression: "'lb://' + serviceId"
          trusted-proxies: "10\\..*|192\\.168\\..*"
          routes:
            - id: favicon_route
              predicates:
                - Path=/favicon.ico
              filters:
                - SetStatus=NO_CONTENT
              uri: no://op
                # 新增：处理 .well-known 路径的路由
            - id: well_known_devtools_route
              predicates:
                - Path=/.well-known/appspecific/com.chrome.devtools.json
              filters:
                - SetStatus=NO_CONTENT
              uri: no://op
#            - id: assembly-service
#              predicates:
#                - Path=/assembly-service/**
#              filters:
#                - RewritePath=/assembly-service/(?<remaining>.*), /${remaining}
#              uri: lb://assembly-service
#            - id: example-service
#              predicates:
#                - Path=/example-service/**
#              filters:
#                - RewritePath=/example-service/(?<remaining>.*), /${remaining}
#              uri: lb://example-service
#            - id: market-data-service
#              predicates:
#                - Path=/market-data-service/**
#              filters:
#                - RewritePath=/market-data-service/(?<remaining>.*), /${remaining}
#              uri: lb://market-data-service


