DROP TABLE IF EXISTS trade_leg_option;
CREATE TABLE trade_leg_option
(
    leg_id             varchar(32)    NOT NULL,
    trade_id           varchar(32)    NOT NULL,
    version_id         integer        NOT NULL,
    leg_role           integer        NOT NULL,
    is_exotic          boolean DEFAULT false,
    side_type          varchar(90),
    pri_ccy            varchar(3)     NOT NULL,
    pri_amt            numeric(32, 6) NOT NULL,
    cnt_ccy            varchar(3)     NOT NULL,
    cnt_amt            numeric(32, 6) NOT NULL,
    strike             numeric(24, 8) NOT NULL,
    value_date         timestamp,
    contract_type      varchar(90),
    option_style       varchar(255),
    option_type        varchar(255),
    option_event       varchar(255),
    notional_amt       numeric(32, 6),
    expiry_date        timestamp,
    expiry_time        timestamp,
    expiry_zone        varchar(90),
    premium_amt        numeric(32, 6),
    premium_ccy        varchar(10),
    premium_date       timestamp,
    fixing_amt         numeric(32, 6),
    fixing_ccy         varchar(10),
    fixing_date        timestamp,
    fixing_rate        numeric(10, 6),
    fees               numeric(32, 6),
    strategy           varchar(90),
    payout_date        timestamp,
    payout_type        varchar(100),
    payout_amt         numeric(32, 6),
    payout_ccy         varchar(10),
    operation_time     timestamp,
    operation_type     varchar(90),
    operation_quantity numeric(32, 6),
    operation_sub_type varchar(255),
    operation_user     varchar(90),
    barrier_type       varchar(90),
    barrier_style      varchar(90),
    barrier_1          numeric(32, 6),
    barrier_2          numeric(32, 6),
    barrier_start_date timestamp,
    barrier_end_date   timestamp,
    knock_time         timestamp,
    knock_rate         numeric(32, 6),
    knock_event        varchar(90),
    usi                varchar(32),
    regulatory_key     varchar(32),
    down_stream_id     varchar(32),
    is_discrete        boolean DEFAULT false,
    PRIMARY KEY (leg_id)
);

