DROP TABLE IF EXISTS trade;
CREATE TABLE trade(
    trade_id varchar(32) NOT NULL,
    revision integer NOT NULL,
    parent_id varchar(32),
    unit_id varchar(32),
    group_id varchar(32),
    matched_id varchar(32),
    msg_id varchar(32),
    downstream_id varchar(32),
    ticket_num varchar(32),
    user_memo varchar(255),
    ccy_pair varchar(32),
    side varchar(32),
    product_group varchar(32),
    product_type varchar(32),
    product_code varchar(32),
    trade_date timestamp,
    trade_type varchar(32),
    buy_sell_type varchar(32),
    trade_status varchar(32),
    allocation_status varchar(32),
    matched_status varchar(32),
    booking_status varchar(32),
    src_deal_id varchar(32),
    src_sys_name varchar(255),
    src_sys_type varchar(32),
    trade_party_code varchar(32),
    trade_party_name varchar(255),
    trade_party_type varchar(32),
    counter_party_code varchar(32),
    counter_party_name varchar(255),
    trade_ccy varchar(10),
    deal_rate numeric(24,6),
    stock_price numeric(24,6),
    metal_flag boolean DEFAULT false,
    value_date timestamp,
    creation_time timestamp,
    booking_time timestamp,
    execution_time timestamp,
    allocation_time timestamp,
    matched_time timestamp,
    cancelled_time timestamp,
    reversion_time timestamp,
    created_by varchar(32),
    created_time timestamp,
    updated_by varchar(32),
    updated_time timestamp,
    activity_status boolean DEFAULT true,
    delete_flag boolean DEFAULT false,
    PRIMARY KEY (trade_id)
);

